name: Build Android

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

       - name: Make Gradlew Executable
        run: chmod +x ./gradlew


      - name: Build with Gradle Wrapper
        run: |
          chmod +x ./gradlew
          ./gradlew --no-daemon assembleRelease

      - name: Upload APK artifacts
        uses: actions/upload-artifact@v4
        with:
          name: release-apks
          path: app/build/outputs/apk/release/*.apk

      - name: Upload AAB artifacts
        uses: actions/upload-artifact@v4
        with:
          name: release-aabs
          path: app/build/outputs/bundle/release/*.aab
